import React, { useState } from 'react';
import { X, UploadCloud, FileText, CheckCircle2, AlertCircle } from 'lucide-react';
import { createRunFromCSV } from '../services/metricsLoader';
import { ExperimentRun } from '../types/experiment';

interface UploadModalProps {
  isOpen: boolean;
  onClose: () => void;
  onLoadRun: (run: ExperimentRun) => void;
}

export const UploadModal: React.FC<UploadModalProps> = ({ isOpen, onClose, onLoadRun }) => {
  const [dragActive, setDragActive] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [fileName, setFileName] = useState<string | null>(null);

  if (!isOpen) return null;

  const handleFiles = (files: FileList | null) => {
    if (!files || files.length === 0) return;
    const file = files[0];
    setFileName(file.name);
    setError(null);

    const reader = new FileReader();
    reader.onload = (e) => {
      try {
        const text = e.target?.result as string;
        const run = createRunFromCSV(file.name.replace('.csv', ''), text);
        if (run.metrics.length === 0) {
          setError('CSV parsed 0 data rows. Check header: step,train_loss,val_loss,train_acc,val_acc');
          return;
        }
        onLoadRun(run);
        onClose();
      } catch (err: any) {
        setError(`Failed to parse CSV: ${err.message}`);
      }
    };
    reader.onerror = () => {
      setError('Failed to read file from disk');
    };
    reader.readAsText(file);
  };

  const handleDrag = (e: React.DragEvent) => {
    e.preventDefault();
    e.stopPropagation();
    if (e.type === 'dragenter' || e.type === 'dragover') {
      setDragActive(true);
    } else if (e.type === 'dragleave') {
      setDragActive(false);
    }
  };

  const handleDrop = (e: React.DragEvent) => {
    e.preventDefault();
    e.stopPropagation();
    setDragActive(false);
    if (e.dataTransfer.files && e.dataTransfer.files[0]) {
      handleFiles(e.dataTransfer.files);
    }
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/80 backdrop-blur-xs p-4">
      <div className="bg-[#0b0e16] border border-[#263147] w-full max-w-lg p-5 font-mono text-xs shadow-2xl relative">
        <button
          onClick={onClose}
          className="absolute top-4 right-4 text-[#8b949e] hover:text-[#e6edf3] cursor-pointer"
        >
          <X className="w-4 h-4" />
        </button>

        <div className="flex items-center gap-2 mb-4 pb-2 border-b border-[#182030]">
          <UploadCloud className="w-4 h-4 text-cyan-400" />
          <h2 className="text-sm font-semibold text-[#e6edf3] uppercase tracking-wider">
            LOAD METRICS.CSV
          </h2>
        </div>

        <p className="text-[11px] text-[#8b949e] mb-4 leading-relaxed">
          Upload any <code className="text-[#c9d1d9]">metrics.csv</code> generated by <code className="text-[#c9d1d9]">src/train.py</code> or your experiment runner. Supports columns: <code className="text-amber-400">step, train_loss, val_loss, train_acc, val_acc</code>.
        </p>

        {/* Drag and drop zone */}
        <div
          onDragEnter={handleDrag}
          onDragLeave={handleDrag}
          onDragOver={handleDrag}
          onDrop={handleDrop}
          className={`border-2 border-dashed p-8 text-center transition-colors cursor-pointer ${
            dragActive
              ? 'border-cyan-400 bg-cyan-950/20'
              : 'border-[#273247] hover:border-[#384663] bg-[#0c1017]'
          }`}
          onClick={() => document.getElementById('csv-file-input')?.click()}
        >
          <input
            id="csv-file-input"
            type="file"
            accept=".csv,text/csv"
            className="hidden"
            onChange={(e) => handleFiles(e.target.files)}
          />

          <FileText className="w-8 h-8 text-[#57606a] mx-auto mb-2" />
          <p className="text-xs text-[#c9d1d9] font-semibold mb-1">
            {fileName || 'Drop metrics.csv here or click to browse'}
          </p>
          <p className="text-[10px] text-[#6e7681]">
            Example path: <code className="text-[#8b949e]">results/paper_regression_100k/seed0_.../metrics.csv</code>
          </p>
        </div>

        {error && (
          <div className="mt-3 p-2.5 bg-rose-950/30 border border-rose-500/40 text-rose-300 text-[11px] flex items-center gap-2">
            <AlertCircle className="w-4 h-4 shrink-0 text-rose-400" />
            <span>{error}</span>
          </div>
        )}

        <div className="mt-4 pt-3 border-t border-[#182030] flex justify-end gap-2">
          <button
            onClick={onClose}
            className="px-3 py-1.5 border border-[#273247] hover:bg-[#161c2b] text-[#8b949e] cursor-pointer"
          >
            CANCEL
          </button>
        </div>
      </div>
    </div>
  );
};

